### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by moonmanbu** [actframework/act-hibernate#2]
**reproduce project**
[https://github.com/moonmanbu/reproduce](url)
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    patch/org/hibernate/validator/Op.<clinit>()V @10: putstatic
  Reason:
    Type 'patch/org/hibernate/validator/Op$1' (current frame, stack[0]) is not assignable to 'patch/org/hibernate/validator/Op'
  Current Frame:
    bci: @10
    flags: { }
    locals: { }
    stack: { 'patch/org/hibernate/validator/Op$1' }
  Bytecode:
    0x0000000: bb00 0f59 1211 03b7 0012 b300 16bb 0018
    0x0000010: 5912 1a04 b700 1bb3 001c bb00 1e59 1220
    0x0000020: 05b7 0021 b300 22bb 0024 5912 2606 b700
    0x0000030: 27b3 0028 07bd 0001 5903 b200 1653 5904
    0x0000040: b200 1c53 5905 b200 2253 5906 b200 2853
    0x0000050: b300 2ab1                              

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at java.lang.Class.getEnumConstantsShared(Class.java:3311)
	at java.lang.Class.enumConstantDirectory(Class.java:3341)
	at java.lang.Enum.valueOf(Enum.java:232)
	at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:483)
	at sun.reflect.annotation.AnnotationParser.parseEnumArray(AnnotationParser.java:744)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:533)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:226)
	at sun.reflect.annotation.AnnotationParser.parseAnnotationArray(AnnotationParser.java:765)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:537)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1150)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1148)
	at java.lang.reflect.Field.getAnnotation(Field.java:1120)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:191)
	at org.hibernate.annotations.common.reflection.java.JavaAnnotationReader.isAnnotationPresent(JavaAnnotationReader.java:50)
	at org.hibernate.annotations.common.reflection.java.JavaXAnnotatedElement.isAnnotationPresent(JavaXAnnotatedElement.java:60)
	at org.hibernate.annotations.common.reflection.java.JavaXMember.isAnnotationPresent(JavaXMember.java:43)
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:258)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:211)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:719)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:245)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:222)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:265)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:875)
	at act.db.hibernate.HibernateService.createEntityManagerFactory(HibernateService.java:83)
	at act.db.jpa.JPAService.createEntityManagerFactory(JPAService.java:248)
	at act.db.jpa.JPAService.dataSourceProvided(JPAService.java:72)
	at act.db.hibernate.HibernateService.dataSourceProvided(HibernateService.java:77)
	at act.db.sql.SqlDbService.doInitDataSource(SqlDbService.java:275)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:257)
	at act.db.sql.SqlDbService.init(SqlDbService.java:118)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:76)
	at act.job.Job$4.apply(Job.java:455)
	at act.job.Job.doJob(Job.java:413)
	at act.job.Job.run(Job.java:337)
	at act.job.Job$LockableJobList$1.run(Job.java:109)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:543)
	at act.job.Job.doJob(Job.java:413)
	at act.job.Job.run(Job.java:337)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zhupingcmm** [comment]
do you have fixed this issue? I have the some issue now.

**Comment by greenlaw110** [comment]
hmm... I will take a look this weekend

**Comment by greenlaw110** [comment]
This one is bit hard. need more time to explore the solution
